[package]
name = "constraint"
version = "0.1.0"
authors = ["Duane Bailey <bailey.d.r@gmail.com>"]
build = "build.rs"

[lib]
name = "constraint"
path = "src/lib.rs"

[dependencies]
prettytable-rs = "0.6.2"
lalrpop-util = "0.12.0"
itertools = "0.4.16"

[build-dependencies]
lalrpop = "0.11.0"
